CREATE TABLE IF NOT EXISTS todo_users(
	name VARCHAR(100) NOT NULL UNIQUE,
	ID INTEGER PRIMARY KEY NOT NULL,
	hash VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS todo_tasks(
	name VARCHAR(100) NOT NULL UNIQUE,
	user_id INTEGER NOT NULL REFERENCES todo_users(ID) ON DELETE CASCADE,
	ID INTEGER PRIMARY KEY NOT NULL,
	done BOOLEAN NOT NULL CHECK(done IN (0, 1)) DEFAULT 0
);
